#!/bin/bash

(make clean; make) || exit 1

total=0
totalmax=0

rm -f total.txt *.out 

# Test driver
function runtest {
  prog=$1
  args=$2
  testinput=$3
  grade=$4


  inputdescr=
  if [ "$testinput" != "none" ]; then
      inputdescr=" < $testinput"
  fi
  descr="$prog $args $inputdescr"
  
  echo "======= $descr ==========="

  #Run tested program
  ./$prog $args > $prog.out
  errorcode=$?
#  if [ $? -ne 0 ]; then
#     echo Cannot run ./$prog
#     cat $prog.out
#     echo "*****Test Failed*****";
#     return
#  fi

  #Run original program
  ./$prog.org $args > $prog.org.out
  orgerrorcode=$?
#  if [ $? -ne 0 ]; then
#     echo Cannot run ./$prog.org
#     cat $prog.org.out
#     echo "*****Test Failed*****";
#     return
#  fi
  if [ $errorcode -ne $orgerrorcode ]; then
      echo Error codes do not match
      echo "*****Test Failed*****";
      return
  fi

  diff $prog.out $prog.org.out > diff.out
  if [ $? -eq 0 ]; then
      cat $prog.out
      echo Test passed...;

  else
      echo "*****Test Failed*****";
      echo ------ Your Output ----------
      cat $prog.out
      echo ------ Expected Output ------
      cat $prog.org.out
      echo ------ Difference -----------
      cat diff.out
      echo -----------------------------

  fi
  echo
}

# List of tests running
runtest convert "2 10" none 5
runtest convert "16 FFF" none 5
runtest convert "10 1754" none 5

rm -f total.txt *.out convert
